### ISSUE TITLE
Rework meilisearch tokenizer

### ISSUE THREAD

**Issue by LegendreM** [meilisearch/Tokenizer#1]
TBD

## Related
https://github.com/meilisearch/MeiliSearch/issues/624

**Comment by djKooks** [comment]
So this project is for replacing tokenizer of MeiliSearch?

**Comment by djKooks** [comment]
@MarinPostma I'm bit interesting on contributing tokenizer part of meilisearch, but not sure whether this project is on work, or this is just for test... 🤔

**Comment by MarinPostma** [comment]
Hey @djKooks ! It is the official tokenizer since the last version, contribution to make language support better are happily accepted 🙂
