### ISSUE TITLE
Handle non-breakable spaces

### ISSUE THREAD

**Issue by curquiza** [meilisearch/Tokenizer#38]
The tokenizer must handle non-breakable spaces.

For example, it should handle the following examples this way:
- `3 456 678` where the ` ` (space) is not considered as a separator
<s>- `Альфа` where `ь` is not considered as space, so a separator</s>

<s>Related to https://github.com/meilisearch/MeiliSearch/issues/1335</s> cf @shekhirin comment

**Comment by shekhirin** [comment]
Hi @curquiza, I think there's no issue with non-breakable spaces, it's all about transcriptions of the Russian words in English 😄  I made a PR fixing that behaviour.

**Comment by curquiza** [comment]
Thanks @shekhirin, but I think we still need to handle breakable non-breakable spaces in the future, so I re-open the issue 🙂
